version: '2'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file: .env
