from ..extensions import db


class Race(db.Model):
    __tablename__ = 'ccf_races'

    track_code = db.Column(db.String(3), primary_key=True)
    race_dt = db.Column(db.String(8), primary_key=True)
    race_num = db.Column(db.Integer, primary_key=True)
    day_eve_flag = db.Column(db.String(1))
    distance = db.Column(db.Numeric(7, 2))
    distance_unit = db.Column(db.String(1))
    about_dist_flag = db.Column(db.String(1), nullable=True)
    surface_1 = db.Column(db.String(1))
    surface_2 = db.Column(db.String(1))
    all_weather_flag = db.Column(db.String(1), nullable=True)
    chute_start_flag = db.Column(db.String(1))
    bris_racetype = db.Column(db.String(2))
    eqb_racetype = db.Column(db.String(5))
    race_grade = db.Column(db.Integer)
    age_sex_restrictions = db.Column(db.String(3))
    race_restrictions_code = db.Column(db.String(20))
    statebred_flag = db.Column(db.String(1))
    race_class = db.Column(db.String(20))
    breed_ind = db.Column(db.String(2))
    country_code = db.Column(db.String(3))
    purse = db.Column(db.Integer)
    total_value = db.Column(db.Integer)
    max_claim_price = db.Column(db.Integer)
    conditions_1 = db.Column(db.String(255))
    conditions_2 = db.Column(db.String(255))
    conditions_3 = db.Column(db.String(255))
    conditions_4 = db.Column(db.String(255))
    conditions_5 = db.Column(db.String(255))
    field_size = db.Column(db.Integer)
    track_condition = db.Column(db.String(2))
    fraction_1 = db.Column(db.Numeric(5, 2))
    fraction_2 = db.Column(db.Numeric(5, 2))
    fraction_3 = db.Column(db.Numeric(5, 2))
    fraction_4 = db.Column(db.Numeric(5, 2))
    fraction_5 = db.Column(db.Numeric(5, 2))
    final_time = db.Column(db.Numeric(5, 2))
    fraction_1d = db.Column(db.Integer)
    fraction_2d = db.Column(db.Integer)
    fraction_3d = db.Column(db.Integer)
    fraction_4d = db.Column(db.Integer)
    fraction_5d = db.Column(db.Integer)
    off_time = db.Column(db.String(5))
    call_start_dist = db.Column(db.Integer)
    call_1_dist = db.Column(db.Integer)
    call_2_dist = db.Column(db.Integer)
    call_3_dist = db.Column(db.Integer)
    race_name = db.Column(db.String(80))
    start_descr = db.Column(db.String(50))
    temp_rail_dist = db.Column(db.Integer)
    off_turf_ind = db.Column(db.String(1))
    off_turf_dist_chg = db.Column(db.String(1))
    weather = db.Column(db.String(65))
    race_temp = db.Column(db.Integer)
    wps_pool = db.Column(db.Integer)
    runup_dist = db.Column(db.Integer)

    @classmethod
    def find_by_track_date(cls, track, dt):
        return Race.query.filter_by(track_code = track, race_dt = dt)


class Starter(db.Model):
    __tablename__ = 'ccf_starters'

    track_code = db.Column(db.String(3), primary_key=True)
    race_dt = db.Column(db.String(8), primary_key=True)
    race_num = db.Column(db.Integer, primary_key=True)
    day_eve_flag = db.Column(db.String(1))
    horse_name = db.Column(db.String(50), primary_key=True)
    foreign_bred_code = db.Column(db.String(5))
    state_bred_code = db.Column(db.String(5))
    post_position = db.Column(db.Integer)
    program_number = db.Column(db.String(3))
    birth_year = db.Column(db.Integer)
    breed = db.Column(db.String(2))
    coupled_flag = db.Column(db.String(1))
    jockey = db.Column(db.String(50), index=True)
    jockey_last = db.Column(db.String(25))
    jockey_first = db.Column(db.String(15))
    jockey_middle = db.Column(db.String(15))
    trainer = db.Column(db.String(50), index=True)
    trainer_last = db.Column(db.String(100))
    trainer_first = db.Column(db.String(15))
    trainer_middle = db.Column(db.String(15))
    trip_comment = db.Column(db.String(22))
    owners = db.Column(db.String(300))
    owner_first = db.Column(db.String(15))
    owner_middle = db.Column(db.String(15))
    claim_price = db.Column(db.Integer)
    medications = db.Column(db.String(7))
    equipment = db.Column(db.String(7))
    earnings = db.Column(db.Integer)
    odds = db.Column(db.Numeric(6, 2))
    non_betting_flag = db.Column(db.String(1))
    favorite_flag = db.Column(db.Integer)
    dq_flag = db.Column(db.String(1))
    dq_placing = db.Column(db.Integer)
    weight = db.Column(db.Integer)
    corrected_weight = db.Column(db.String(1))
    overweight_amount = db.Column(db.Integer)
    claimed_ind = db.Column(db.String(1), index=True)
    claimed_by_trainer = db.Column(db.String(30))
    claimed_by_trainer_last = db.Column(db.String(25))
    claimed_by_trainer_first = db.Column(db.String(15))
    claimed_by_trainer_middle = db.Column(db.String(15))
    claimed_by_owner = db.Column(db.String(300))
    claimed_by_owner_last = db.Column(db.String(100))
    claimed_by_owner_first = db.Column(db.String(15))
    claimed_by_owner_middle = db.Column(db.String(15))
    win_payoff = db.Column(db.Numeric(6, 2))
    place_payoff = db.Column(db.Numeric(6, 2))
    show_payoff = db.Column(db.Numeric(6, 2))
    call_start_pos = db.Column(db.Integer)
    call_1_pos = db.Column(db.Integer)
    call_2_pos = db.Column(db.Integer)
    call_3_pos = db.Column(db.Integer)
    stretch_pos = db.Column(db.Integer)
    finish_pos = db.Column(db.Integer)
    official_finish_pos = db.Column(db.Integer)
    call_start_la = db.Column(db.Numeric(5, 2))
    call_1_la = db.Column(db.Numeric(5, 2))
    call_2_la = db.Column(db.Numeric(5, 2))
    call_3_la = db.Column(db.Numeric(5, 2))
    stretch_la = db.Column(db.Numeric(5, 2))
    finish_la = db.Column(db.Numeric(5, 2))
    call_start_lb = db.Column(db.Numeric(5, 2))
    call_1_lb = db.Column(db.Numeric(5, 2))
    call_2_lb = db.Column(db.Numeric(5, 2))
    call_3_lb = db.Column(db.Numeric(5, 2))
    stretch_lb = db.Column(db.Numeric(5, 2))
    finish_lb = db.Column(db.Numeric(5, 2))
    call_start_margin = db.Column(db.Numeric(5, 2))
    call_1_margin = db.Column(db.Numeric(5, 2))
    call_2_margin = db.Column(db.Numeric(5, 2))
    call_3_margin = db.Column(db.Numeric(5, 2))
    stretch_margin = db.Column(db.Numeric(5, 2))
    finish_margin = db.Column(db.Numeric(5, 2))
    dh_flag = db.Column(db.String(2))
    horse_reg_id = db.Column(db.String(8))
    jockey_id = db.Column(db.Integer)
    trainer_id = db.Column(db.Integer)
    owner_id = db.Column(db.Integer)
    claimed_by_trainer_id = db.Column(db.Integer)
    claimed_by_owner_id = db.Column(db.Integer)
    eqb_ref_name = db.Column(db.Integer)
    void_ind = db.Column(db.String(1))
    void_reason = db.Column(db.String(1))

    @classmethod
    def find_by_track_date(cls, track, dt):
        return Starter.query.filter_by(track_code = track, race_dt = dt)


class Track(db.Model):
    __tablename__ = 'tracks'

    track_code = db.Column(db.String(3), primary_key=True)
    ccf_code = db.Column(db.String(3), primary_key=True)
    track_nm = db.Column(db.String(25))

    @classmethod
    def find_by_ccf(cls, cd):
        return Track.query.filter_by(ccf_code = cd).first()
