CREATE OR REPLACE VIEW ccf_vw AS
SELECT a.track_code,
  a.race_dt,
  a.race_num,
  a.day_eve_flag,
  a.distance,
  ROUND(a.distance/220, 1) furlongs,
  CASE WHEN a.about_dist_flag = 'A' THEN 1 ELSE 0 END is_about_distance,
  CASE WHEN a.distance >= 1760 THEN 1 ELSE 0 END is_route,
  a.surface_2 surface,
  CASE WHEN UPPER(a.surface_2) = 'D' THEN 1 ELSE 0 END is_dirt,
  CASE WHEN UPPER(a.surface_2) = 'T' THEN 1 ELSE 0 END is_turf,
  CASE WHEN a.surface_2 = 'A' THEN 1 ELSE 0 END is_allweather,
  CASE WHEN UPPER(a.chute_start_flag) = 'C' THEN 1 ELSE 0 END is_chute_start,
  a.bris_racetype,
  a.eqb_racetype,
  CASE WHEN a.bris_racetype IN ('S', 'M', 'MO') THEN 1 ELSE 0 END is_maiden_race,
  a.race_grade,
  CASE WHEN a.race_grade > 0 THEN 1 ELSE 0 END is_graded_stakes_race,
  CASE WHEN a.bris_racetype = 'N' THEN 1 ELSE 0 END is_stakes_race,
  a.age_sex_restrictions,
  a.race_restrictions_code,
  CASE WHEN UPPER(a.statebred_flag) = 'S' THEN 1 ELSE 0 END is_statebred,
  a.race_class,
  a.breed_ind,
  a.country_code,
  a.purse,
  a.total_value,
  a.max_claim_price,
  (a.conditions_1 || COALESCE(a.conditions_2, '') || COALESCE(a.conditions_3, '') || 
  COALESCE(a.conditions_4, '') || COALESCE(a.conditions_5, '')) conditions,
  a.field_size,
  a.track_condition,
  a.fraction_1,
  a.fraction_2,
  a.fraction_3,
  a.fraction_4,
  a.fraction_5,
  a.final_time,
  a.fraction_1d,
  a.fraction_2d,
  a.fraction_3d,
  a.fraction_4d,
  a.fraction_5d,
  a.off_time,
  a.call_start_dist,
  a.call_1_dist,
  a.call_2_dist,
  a.call_3_dist,
  a.race_name,
  a.start_descr,
  a.temp_rail_dist,
  CASE WHEN UPPER(a.off_turf_ind) = 'O' THEN 1 ELSE 0 END is_off_turf,
  CASE
    WHEN UPPER(a.off_turf_dist_chg) = 'Y' THEN 1
    WHEN UPPER(a.off_turf_dist_chg) = 'N' THEN 0
    ELSE null
  END is_off_turf_dist_chg,
  a.weather,
  a.race_temp,
  a.wps_pool,
  a.runup_dist,
  b.horse_name,
  b.foreign_bred_code,
  b.state_bred_code,
  b.post_position,
  b.program_number,
  b.birth_year,
  b.breed,
  b.coupled_flag,
  b.jockey,
  b.trainer,
  b.trip_comment,
  b.owners,
  b.claim_price,
  CASE WHEN b.claim_price > 0 THEN 1 ELSE 0 END is_claiming_race,
  b.medications,
  CASE WHEN b.medications LIKE '%L%' OR b.medications LIKE '%M%' THEN 1 ELSE 0 END has_lasix,
  b.equipment,
  CASE WHEN b.equipment LIKE '%B%' THEN 1 ELSE 0 END has_blinkers,
  b.earnings,
  b.odds,
  CASE WHEN b.non_betting_flag = 'Y' THEN 1 ELSE 0 END is_nonbetting,
  b.favorite_flag is_favorite,
  CASE WHEN b.dq_flag = 'Y' THEN 1 ELSE 0 END is_dq,
  b.dq_placing,
  b.weight,
  b.corrected_weight,
  b.overweight_amount,
  CASE WHEN b.claimed_ind = 'Y' THEN 1 ELSE 0 END is_claimed,
  b.claimed_by_trainer,
  b.claimed_by_owner,
  b.win_payoff,
  b.place_payoff,
  b.show_payoff,
  COALESCE(b.win_payoff, 0) - 2.0 win_profit,
  COALESCE(b.win_payoff, 0) + COALESCE(b.place_payoff, 0) + COALESCE(b.show_payoff, 0) - 6.0 itm_profit,
  b.call_start_pos,
  b.call_1_pos,
  b.call_2_pos,
  b.call_3_pos,
  b.stretch_pos,
  b.finish_pos,
  b.official_finish_pos,
  b.call_start_la,
  b.call_1_la,
  b.call_2_la,
  b.call_3_la,
  b.stretch_la,
  b.finish_la,
  b.call_start_lb,
  b.call_1_lb,
  b.call_2_lb,
  b.call_3_lb,
  b.stretch_lb,
  b.finish_lb,
  b.call_start_margin,
  b.call_1_margin,
  b.call_2_margin,
  b.call_3_margin,
  b.stretch_margin,
  b.finish_margin,
  CASE WHEN b.dh_flag = 'DH' THEN 1 ELSE 0 END is_deadheat,
  CASE WHEN b.void_ind = 'Y' THEN 1 ELSE 0 END is_void_claim,
  b.void_reason,
  current_date - to_date(a.race_dt, 'YYYYMMDD') days_since_race,
  EXTRACT(year FROM to_date(a.race_dt, 'YYYYMMDD')) race_year,
  EXTRACT(month FROM to_date(a.race_dt, 'YYYYMMDD')) race_month,
  ROW_NUMBER() OVER (PARTITION BY b.trainer ORDER BY b.race_dt DESC, b.race_num DESC) rn_trainer,
  ROW_NUMBER() OVER (PARTITION BY b.jockey ORDER BY b.race_dt DESC, b.race_num DESC) rn_jockey,
  ROW_NUMBER() OVER (PARTITION BY b.trainer, b.jockey ORDER BY b.race_dt DESC, b.race_num DESC) rn_trainer_jockey,
  ROW_NUMBER() OVER (PARTITION BY b.horse_name ORDER BY b.race_dt DESC, b.race_num DESC) rn_horse
FROM ccf_races a 
INNER JOIN ccf_starters b 
  ON b.track_code = a.track_code AND 
     b.race_dt = a.race_dt AND
     b.race_num = a.race_num
WHERE b.program_number <> 'SCR';
